const IS_EMAIL = 'IS_EMAIL'
const IS_LETTERS_ONLY = 'IS_LETTERS_ONLY'
const IS_LENGTH =  'IS_LENGTH'
const IS_BIGGER_THEN = 'IS_BIGGER_THEN'
const IS_SMALLER_THEN = 'IS_SMALLER_THEN'
const IS_EMPTY = 'IS_EMPTY'
const IS_NOT_EMPTY = 'IS_NOT_EMPTY'
const IS_NUMERIC_ONLY = 'IS_NUMERIC_ONLY'
const IS_DATE = 'IS_DATE'
const IS_MOBILE_PHONE = 'IS_MOBILE_PHONE'
const IS_CREDIT_CARD = 'IS_CREDIT_CARD'
const IS_URL = 'IS_URL'
const IS_URLS = 'IS_URL_ARRAY'
const IS_WORDS = 'IS_WORDS'

module.exports = {
    IS_EMAIL,
    IS_LETTERS_ONLY,
    IS_LENGTH,
    IS_BIGGER_THEN,
    IS_SMALLER_THEN,
    IS_EMPTY,
    IS_NOT_EMPTY,
    IS_NUMERIC_ONLY,
    IS_DATE,
    IS_MOBILE_PHONE,
    IS_CREDIT_CARD,
    IS_URL,
    IS_URLS,
    IS_WORDS
}