const IS_EMAIL = 'IS_EMAIL'
const IS_LETTERS_ONLY = 'IS_LETTERS_ONLY'
const IS_LENGTH = 'IS_LENGTH'
const IS_BIGGER_THAN = 'IS_BIGGER_THAN'
const IS_SMALLER_THAN = 'IS_SMALLER_THAN'
const IS_EMPTY = 'IS_EMPTY'
const IS_REQUIRED = 'IS_REQUIRED'
const IS_NUMERIC_ONLY = 'IS_NUMERIC_ONLY'
const IS_DATE = 'IS_DATE'
const IS_MOBILE_PHONE = 'IS_MOBILE_PHONE'
const IS_CREDIT_CARD = 'IS_CREDIT_CARD'
const IS_URL = 'IS_URL'
const IS_URLS = 'IS_URL_ARRAY'
const IS_WORDS = 'IS_WORDS'
const IS_AFTER = 'IS_AFTER'
const isISO8601 = 'isISO8601'
module.exports = {
    IS_EMAIL,
    IS_LETTERS_ONLY,
    IS_LENGTH,
    IS_BIGGER_THAN,
    IS_SMALLER_THAN,
    IS_EMPTY,
    IS_REQUIRED,
    IS_NUMERIC_ONLY,
    IS_DATE,
    IS_MOBILE_PHONE,
    IS_CREDIT_CARD,
    IS_URL,
    IS_URLS,
    IS_WORDS,
    IS_AFTER,
    isISO8601
}